name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the Node.js version

      - name: Install dependencies
        run: npm install  # Install npm dependencies

      - name: Run tests
        run: npm test  # Run your tests

  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    needs: build  # Ensure the build job completes successfully before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Firebase CLI Setup
        uses: wzieba/Firebase-Hosting-Github-Action@v0.9.0  # Set up Firebase CLI
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Use a secret for Firebase Service Account

      - name: Deploy to Firebase Hosting
        run: firebase deploy --project your-firebase-project-id --token ${{ secrets.FIREBASE_TOKEN }}  # Deploy to Firebase
